### ISSUE TITLE
npm-debug.log

### ISSUE THREAD

**Issue by YoutubeNico77171** [volca780/TwitchBotStream#3]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle twitchbotstream@1.1.1~prestart: twitchbotstream@1.1.1
6 silly lifecycle twitchbotstream@1.1.1~prestart: no script for prestart, continuing
7 info lifecycle twitchbotstream@1.1.1~start: twitchbotstream@1.1.1
8 verbose lifecycle twitchbotstream@1.1.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle twitchbotstream@1.1.1~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/nicolas/Téléchargements/TwitchBotStream-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle twitchbotstream@1.1.1~start: CWD: /home/nicolas/Téléchargements/TwitchBotStream-master
11 silly lifecycle twitchbotstream@1.1.1~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle twitchbotstream@1.1.1~start: Returned: code: 1  signal: null
13 info lifecycle twitchbotstream@1.1.1~start: Failed to exec start script
14 verbose stack Error: twitchbotstream@1.1.1 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid twitchbotstream@1.1.1
16 verbose cwd /home/nicolas/Téléchargements/TwitchBotStream-master
17 error Linux 5.3.0-51-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error twitchbotstream@1.1.1 start: `node server.js`
22 error Exit status 1
23 error Failed at the twitchbotstream@1.1.1 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the twitchbotstream package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs twitchbotstream
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls twitchbotstream
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by YoutubeNico77171** [comment]
je suis sur linux

**Comment by YoutubeNico77171** [comment]
nicolas@nicolas-HP-255-G5-Notebook-PC:~/Téléchargements/TwitchBotStream-master$ npm start

> twitchbotstream@1.1.1 start /home/nicolas/Téléchargements/TwitchBotStream-master
> node server.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nicolas/Téléchargements/TwitchBotStream-master/server.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

npm ERR! Linux 5.3.0-51-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! twitchbotstream@1.1.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twitchbotstream@1.1.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the twitchbotstream package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs twitchbotstream
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls twitchbotstream
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nicolas/Téléchargements/TwitchBotStream-master/npm-debug.log

**Comment by YoutubeNico77171** [comment]
nicolas@nicolas-HP-255-G5-Notebook-PC:~/Téléchargements/TwitchBotStream-master$ node server.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nicolas/Téléchargements/TwitchBotStream-master/server.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
